apiVersion: v1
kind: Service
metadata:
    labels:
        app: api-gateway
    name: api-gateway
    namespace: microsys
spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 80
    selector:
        app: api-gateway
    type: NodePort
 
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: api-gateway-deployment
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: api-gateway
        spec:
            containers:
            - name: api-gateway
                image: harbor.nicajonh.com:8180/labdev/api-gateway-zuul:latest
                imagePullPolicy: IfNotPresent
                args: ["--spring.profiles.active=$(DEPLOYMENT_ENV_KEY)"]
                ports:
                    - containerPort: 8083
            env:
            - name: DEPLOYMENT_ENV_KEY
                valueFrom:
                    configMapKeyRef:
                    name: microsys-config
                    key: DEPLOYMENT_EN

 