apiVersion: v1
kind: Service
metadata:
    labels:
        app: course-service
    name: course-service
    namespace: microsys
spec:
    ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
        app: course-service
    type: ClusterIP
 
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: course-service-deployment
    namespace: microsys
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: course-service
        spec:
            containers:
            - name: course-service
                image: harbor.nicajonh.com:8180/labdev/course-service:latest
                imagePullPolicy: IfNotPresent
                args: ["--spring.profiles.active=${DEPLOYMENT_ENV_KEY}"]
                ports:
                - containerPort: 20880
                env:
                - name: DEPLOYMENT_ENV_KEY
                    valueFrom:
                        configMapRef:
                        name: microsys-config
                        key: DEPLOYMENT_ENV

            - name: course-edge-service
                image: harbor.nicajonh.com:8180/labdev/course-edge-service:latest
                imagePullPolicy: IfNotPresent
                    args: ["--spring.profiles.active=$(DEPLOYMENT_ENV_KEY)"]
                ports:
                - containerPort: 8085
                env:
                - name: DEPLOYMENT_ENV_KEY
                    valueFrom:
                        configMapRef:
                        name: microsys-config
                        key: DEPLOYMENT_ENV
    