apiVersion: v1
kind: Service
metadata:
    labels:
        app: message-service
    name: message-service
    namespace: microsys
spec:
    ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
    selector:
        app: message-service
    type: ClusterIP
 
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: message-service-deployment
    namespace: microsys
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: message-service
        spec:
            containers:
            - name: message-service
                image: harbor.nicajonh.com:8180/labdev/message-service:latest
                imagePullPolicy: IfNotPresent
                args: ["--spring.profiles.active=$(DEPLOYMENT_ENV_KEY)"]
              ports:
              - containerPort: 9090
            env:
                - name: DEPLOYMENT_ENV_KEY
                valueFrom:
                    configMapRef:
                        name: microsys-config
                        key: DEPLOYMENT_ENV
                
 