apiVersion: v1
kind: Service
metadata:
    labels:
        app: user-service
    name: user-service
    namespace: microsys
spec:
    ports:
    - name: user-edge-service-port
      port: 8082
      protocol: TCP
      targetPort: 8082
    - name: user-service-port
      port: 7911
      protocol: TCP
      targetPort: 7911
    selector:
        app: user-service
    sessionAffinity: None
    type: ClusterIP
 
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: user-service-deployment
    namespace: microsys
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: user-service
        spec:
            containers:
            - name: user-service
                image: harbor.nicajonh.com:8180/labdev/user-service:latest
                imagePullPolicy: IfNotPresent
                args: ["--spring.profiles.active=$(DEPLOYMENT_ENV_KEY)"]
              ports:
              - containerPort: 7911
            env:
                - name: DEPLOYMENT_ENV_KEY
                valueFrom:
                    configMapKeyRef:
                    name: microsys-config
                    key: DEPLOYMENT_EN
              
             containers:
            - name: user-edge-service
                image: harbor.nicajonh.com:8180/labdev/user-edge-service:latest
                imagePullPolicy: IfNotPresent
                args: ["--spring.profiles.active=$(DEPLOYMENT_ENV_KEY)"]
                ports:
                - containerPort: 8083
                env:
                - name: DEPLOYMENT_ENV_KEY
                    valueFrom:
                        configMapKeyRef:
                        name: microsys-config
                        key: DEPLOYMENT_EN

              
 